### ISSUE TITLE
Memory index is out of range

### ISSUE THREAD

**Issue by grahamehorner** [unoplatform/Uno.Playground#98] opened 2020-01-10 13:29 UTC
Live demo returning an error :-

 Unhandled dispatcher exception: RuntimeError: Memory index is out of range (RuntimeError: Memory index is out of range
   at Module[_mono_wasm_invoke_method] (https://playground.platform.uno/mono.js:1:220383)
   at BINDING.call_method (https://playground.platform.uno/mono.js:1:162428)
   at Anonymous function (https://playground.platform.uno/mono.js:1:164787)
   at Anonymous function (https://playground.platform.uno/Uno.UI.js:79:33))

**Comment by jeromelaban** [comment] 2020-01-10 14:11
Thank you, this issue is a duplicate of https://github.com/unoplatform/uno/issues/1451. This may be fixed by a later version of mono or emscripten.

**Closed by jeromelaban** 2020-01-10 14:11 UTC
